---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options
# See https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md for configuration options

title: "Demo dashboard"
subtitle: "Homer"
logo: "assets/icons/pwa-512x512.png"
icon: "fas fa-gears"

header: true
footer: '<p>Created with <span class="has-text-danger"><i class="fas fa-box-open"></i></span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a>, <a href="https://fontawesome.com/">font awesome</a>, <a href="https://podman.io/">podman</a> & <a href="https://github.com/bastienwirtz/homer">homer</a> // Fork me on <a href="https://github.com/brunothg/homer-dock"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.


links:
  - name: ""
    icon: "fas fa-gear"
    url: "config/dashboard.exec"
    target: "_self"

message:
  url: assets/message.json
  refreshInterval: 60000

services:
  - name: "Websites"
    icon: "fas fa-cloud"
    items:
      - name: "Podman"
        subtitle: "Daemonless OCI containers"
        icon: "fas fa-box"
        tag: "web"
        keywords: "self hosted reddit"
        url: "https://podman.io/"
        target: "_blank" # optional html a tag target attribute
      - name: "Homer"
        subtitle: "Static dashboard for your server"
        icon: "fas fa-circle-dot"
        tag: "web"
        url: "https://github.com/bastienwirtz/homer"
        target: "_blank"
